modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="singlechunk"
version="1.0.0"
displayName="Single Chunk"
authors="i-is-evil-duck"
description="Only the spawn chunk is generated and loaded. Everything else is void. Players can move freely into the void."

[[dependencies.singlechunk]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.singlechunk]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
